### ISSUE TITLE
JS stack trace not added to DuktapeException when a proxy is used

### ISSUE THREAD

**Issue by Egorand** [square/duktape-android#159]
Java stack trace gets populated properly if the exception is thrown as the result of a call to `Duktape.evaluate()`:
```kotlin
duktape.evaluate("""
    1 + 1
    1 + 2
    1 + z
    """.trimIndent(), "test.js")
```
produces:
```java
com.squareup.duktape.DuktapeException: ReferenceError: identifier 'z' undefined
    at JavaScript.eval(test.js:3)
    at com.squareup.duktape.Duktape.evaluate(Native Method)
    at com.squareup.duktape.Duktape.evaluate(Duktape.java:60)
    at com.squareup.duktapestacktrace.DuktapeCaller.call(DuktapeCaller.kt:25)
```
However, if the code is executed through a proxy, the JS part of the trace is missing.
```kotlin
duktape.evaluate("""
    function ad(a, b) {
      return a + b;
    }
    """.trimIndent())
duktape.evaluate("""
    var Adder = {
      add: function(a, b) {
        return add(a, b);
      }
    };
    """.trimIndent(), "test.js")
val adder = duktape.get("Adder", Adder::class.java)
return adder.add(1, 2)
```
produces:
```java
com.squareup.duktape.DuktapeException: ReferenceError: identifier 'add' undefined
    at com.squareup.duktape.Duktape.call(Native Method)
    at com.squareup.duktape.Duktape.access$100(Duktape.java:28)
    at com.squareup.duktape.Duktape$1.invoke(Duktape.java:139)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy0.add(Unknown Source)
    at com.squareup.duktapestacktrace.DuktapeCaller.call(DuktapeCaller.kt:24)
```
The reason is likely that the code in `DuktapeException` is looking for the `evaluate` call in the trace, which is missing from the second example.

**Comment by JakeWharton** [comment]
Reopening for QuickJS version

**Comment by szurbrigg** [comment]
QuickJS version: https://github.com/square/duktape-android/pull/166
