### ISSUE TITLE
Exception when trying to throw exception

### ISSUE THREAD

**Issue by mattprecious** [square/duktape-android#69]
The JS is throwing an exception and Duktape is throwing when trying to handle it.

```
A/art: art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception com.squareup.duktape.DuktapeException: DoubleError: error in error handling
A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Object com.squareup.duktape.Duktape.call(long, long, java.lang.Object, java.lang.Object[]) (Duktape.java:-2)
A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Object com.squareup.duktape.Duktape.access$100(long, long, java.lang.Object, java.lang.Object[]) (Duktape.java:29)
A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Object com.squareup.duktape.Duktape$1.invoke(java.lang.Object, java.lang.reflect.Method, java.lang.Object[]) (Duktape.java:131)
A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Object java.lang.reflect.Proxy.invoke(java.lang.reflect.Proxy, java.lang.reflect.Method, java.lang.Object[]) (Proxy.java:393)
```

```
art  F  art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: thread Thread[71,tid=4643,Native,Thread*=0xda16a400,peer=0x13253400,"RxIoScheduler-34"] using JNIEnv* from thread Thread[71,tid=4643,Native,T
        hread*=0xda16a400,peer=0x13253400,"RxIoScheduler-34"]
     F  art/runtime/java_vm_ext.cc:410]     in call to FindClass
     F  art/runtime/java_vm_ext.cc:410]     from java.lang.Object com.squareup.duktape.Duktape.call(long, long, java.lang.Object, java.lang.Object[])
     F  art/runtime/java_vm_ext.cc:410] "RxIoScheduler-34" daemon prio=5 tid=71 Runnable
     F  art/runtime/java_vm_ext.cc:410]   | group="main" sCount=0 dsCount=0 obj=0x13253400 self=0xda16a400
     F  art/runtime/java_vm_ext.cc:410]   | sysTid=4643 nice=0 cgrp=default sched=0/0 handle=0xd94b0930
     F  art/runtime/java_vm_ext.cc:410]   | state=R schedstat=( 19140299 26291000 41 ) utm=0 stm=1 core=1 HZ=100
     F  art/runtime/java_vm_ext.cc:410]   | stack=0xd93ae000-0xd93b0000 stackSize=1038KB
     F  art/runtime/java_vm_ext.cc:410]   | held mutexes= "mutator lock"(shared held)
     F  art/runtime/java_vm_ext.cc:410]   native: #00 pc 0058b0e2  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::ArtMethod*, void*)+2
        26)
     F  art/runtime/java_vm_ext.cc:410]   native: #01 pc 00550d2e  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+286)
     F  art/runtime/java_vm_ext.cc:410]   native: #02 pc 003a489f  /system/lib/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1247)
     F  art/runtime/java_vm_ext.cc:410]   native: #03 pc 003a5f1c  /system/lib/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, char*)+116)
     F  art/runtime/java_vm_ext.cc:410]   native: #04 pc 00163a10  /system/lib/libart.so (art::ScopedCheck::AbortF(char const*, ...)+62)
     F  art/runtime/java_vm_ext.cc:410]   native: #05 pc 0016d90c  /system/lib/libart.so (art::ScopedCheck::CheckThread(_JNIEnv*)+1692)
     F  art/runtime/java_vm_ext.cc:410]   native: #06 pc 0016e4e1  /system/lib/libart.so (art::ScopedCheck::Check(art::ScopedObjectAccess&, bool, char const*, art::JniValueType*) (.constprop.114)+1489)
     F  art/runtime/java_vm_ext.cc:410]   native: #07 pc 001721e5  /system/lib/libart.so (art::CheckJNI::FindClass(_JNIEnv*, char const*)+601)
     F  art/runtime/java_vm_ext.cc:410]   native: #08 pc 00046200  /data/app/com.squareup.cash.beta.debug-2/lib/x86/libduktape.so (???)
     F  art/runtime/java_vm_ext.cc:410]   native: #09 pc 00041970  /data/app/com.squareup.cash.beta.debug-2/lib/x86/libduktape.so (???)
     F  art/runtime/java_vm_ext.cc:410]   native: #10 pc 000412c0  /data/app/com.squareup.cash.beta.debug-2/lib/x86/libduktape.so (???)
     F  art/runtime/java_vm_ext.cc:410]   native: #11 pc 00040f4c  /data/app/com.squareup.cash.beta.debug-2/lib/x86/libduktape.so (???)
     F  art/runtime/java_vm_ext.cc:410]   native: #12 pc 00045f18  /data/app/com.squareup.cash.beta.debug-2/lib/x86/libduktape.so (Java_com_squareup_duktape_Duktape_call+72)
     F  art/runtime/java_vm_ext.cc:410]   native: #13 pc 011b4d1e  /data/app/com.squareup.cash.beta.debug-2/oat/x86/base.odex (java.lang.Object com.squareup.duktape.Duktape.call(long, long, java.lang.Object, java.lan
        g.Object[])+194)
     F  art/runtime/java_vm_ext.cc:410]   native: #14 pc 011b4af7  /data/app/com.squareup.cash.beta.debug-2/oat/x86/base.odex (java.lang.Object com.squareup.duktape.Duktape.access$100(long, long, java.lang.Object, ja
        va.lang.Object[])+91)
     F  art/runtime/java_vm_ext.cc:410]   native: #15 pc 011b474c  /data/app/com.squareup.cash.beta.debug-2/oat/x86/base.odex (java.lang.Object com.squareup.duktape.Duktape$1.invoke(java.lang.Object, java.lang.reflec
        t.Method, java.lang.Object[])+352)
     F  art/runtime/java_vm_ext.cc:410]   native: #16 pc 0035c2f5  /data/dalvik-cache/x86/system@framework@boot.oat (???)
     F  art/runtime/java_vm_ext.cc:410]   at com.squareup.duktape.Duktape.call(Native method)
     F  art/runtime/java_vm_ext.cc:410]   at com.squareup.duktape.Duktape.access$100(Duktape.java:29)
     F  art/runtime/java_vm_ext.cc:410]   at com.squareup.duktape.Duktape$1.invoke(Duktape.java:131)
     F  art/runtime/java_vm_ext.cc:410]   at java.lang.reflect.Proxy.invoke(Proxy.java:393)
```

**Comment by szurbrigg** [comment]
Fixed in https://github.com/square/duktape-android/pull/74.
