### ISSUE TITLE
DuktapeException: TypeError: cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by badboy-tian** [square/duktape-android#98]
```
   Caused by: com.squareup.duktape.DuktapeException: TypeError: cannot read property 'prototype' of undefined
                                                                    at JavaScript.runInContext(?:43226)
                                                                    at JavaScript.s(?:1)
                                                                    at com.squareup.duktape.Duktape.evaluate(Native Method)
                                                                    at com.squareup.duktape.Duktape.evaluate(Duktape.java:69)
```

here is my code:
```
val duktape = Duktape.create()
        try {
            duktape.evaluate(assets.open("bundle.js").reader(Charset.forName("UTF-8")).readText())
            LogHelper.LogE("--->" + duktape.evaluate("generateAddress").toString())
        } finally {
            duktape.close()
        }
```

```
Address.prototype.isPayToScriptHash = function() {
  return this.type === Address.PayToScriptHash;
};
```

**Comment by szurbrigg** [comment]
Hmmm... has `Address` been initialized in your js?  It sounds like it's still undefined.

**Comment by tianqiujie** [comment]
I use the android webview, it is no error
```
<html>
<head>
    <script type="text/javascript" language="javascript" src="bundle.js" charset="UTF-8"></script>
</head>
<body>
<script>
   var data = generateAddress();
   control.generateAddressJs(data[0], data[1], data[2], data[3]);
</script>
</body>
</html>

```

**Comment by JakeWharton** [comment]
Because `Address` is a DOM type. Duktape is not a browser and has no DOM therefore has no `Address` type.

**Comment by tianqiujie** [comment]
@JakeWharton  Thank for your replay
```
// main bitcoin library
bitcore.Address = require('./lib/address');
bitcore.Block = require('./lib/block');
bitcore.MerkleBlock = require('./lib/block/merkleblock');
bitcore.BlockHeader = require('./lib/block/blockheader');
bitcore.HDPrivateKey = require('./lib/hdprivatekey.js');
bitcore.HDPublicKey = require('./lib/hdpublickey.js');
bitcore.Networks = require('./lib/networks');
bitcore.Opcode = require('./lib/opcode');
bitcore.PrivateKey = require('./lib/privatekey');
bitcore.PublicKey = require('./lib/publickey');
bitcore.Script = require('./lib/script');
bitcore.Transaction = require('./lib/transaction');
bitcore.URI = require('./lib/uri');
bitcore.Unit = require('./lib/unit');
```

the Address  is a DOM type ?

**Comment by JakeWharton** [comment]
No. It'd be that type.

Can you provide a minimal failing test case of what you're trying to accomplish?

**Comment by tianqiujie** [comment]
@JakeWharton 
OK, I just want to call js in android
[](https://github.com/bitpay/bitcore-mnemonic) this js library.  and i use Duktape library to make this happen, but failed

```
var Mnemonic = require('bitcore-mnemonic');
var code = new Mnemonic(Mnemonic.Words.SPANISH);
code.toString(); // natal hada sutil año sólido papel jamón combate aula flota ver esfera...
var xpriv = code.toHDPrivateKey();
```

I just want to get the ```toHDPrivateKey```

**Comment by JakeWharton** [comment]
And are you loading the bitcore-mnemonic JS prior to running that?
